
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author JorgeLuis
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() throws IOException {
        initComponents();
        universos = new ArrayList();
        new Universo("KM1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearU = new javax.swing.JDialog();
        jb_agregarS = new javax.swing.JButton();
        jb_guardarU = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_raza = new javax.swing.JTextField();
        tf_planet = new javax.swing.JTextField();
        sp_edad = new javax.swing.JSpinner();
        sp_ki = new javax.swing.JSpinner();
        jb_crearU = new javax.swing.JButton();

        jd_crearU.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_agregarS.setText("Agregar Ser");
        jb_agregarS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarSMouseClicked(evt);
            }
        });
        jd_crearU.getContentPane().add(jb_agregarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jb_guardarU.setText("Guardar y Salir");
        jb_guardarU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarUMouseClicked(evt);
            }
        });
        jd_crearU.getContentPane().add(jb_guardarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        jButton3.setText("Salir");
        jd_crearU.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel1.setText("Creación de Ser");
        jd_crearU.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 15, -1, -1));

        jLabel2.setText("Raza");
        jd_crearU.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 60, -1, -1));

        jLabel3.setText("Ki");
        jd_crearU.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 110, -1, -1));

        jLabel4.setText("Edad Max");
        jd_crearU.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 162, -1, -1));

        jLabel5.setText("Planeta");
        jd_crearU.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 209, -1, -1));
        jd_crearU.getContentPane().add(tf_raza, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 130, -1));
        jd_crearU.getContentPane().add(tf_planet, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 130, -1));
        jd_crearU.getContentPane().add(sp_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 70, -1));
        jd_crearU.getContentPane().add(sp_ki, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 70, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_crearU.setText("Crear Universo");
        jb_crearU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearUMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jb_crearU)
                .addContainerGap(257, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jb_crearU)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_crearUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearUMouseClicked
        String nombre_u = JOptionPane.showInputDialog(
                "Ingrese el nombre del nuevo universo:");
        if (!nombre_u.equals("")) {
            this.jd_crearU.pack();
            this.jd_crearU.setModal(true);
            this.jd_crearU.setVisible(true);
            this.jd_crearU.setLocationRelativeTo(this);
        }
    }//GEN-LAST:event_jb_crearUMouseClicked

    private void jb_agregarSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarSMouseClicked
        try {
            enCreacion = new Universo();
            try {
                if (!this.tf_raza.equals("")
                        || !this.tf_planet.equals("")
                        || (int) this.sp_edad.getValue() < 1
                        || (int) this.sp_ki.getValue() < 1) {
                    enCreacion.addSer(new Ser(
                            tf_raza.getText(),
                            (int) sp_ki.getValue(),
                            (int) sp_edad.getValue(),
                            tf_planet.getText()
                    )
                    );
                    tf_raza.setText("");
                    sp_ki.setValue(100);
                    sp_edad.setValue(50);
                    tf_planet.setText("");
                } else {
                    JOptionPane.showMessageDialog(this.jd_crearU, ""
                            + "Hay campos vacios, porfavor llénelos");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this.jd_crearU,
                        "Ocurrió un error y no se agregó al ser");
            }
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_agregarSMouseClicked

    private void jb_guardarUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarUMouseClicked
        try {
            enCreacion.escribirArchivo();
            tf_raza.setText("");
            sp_ki.setValue(100);
            sp_edad.setValue(50);
            tf_planet.setText("");
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_guardarUMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jb_agregarS;
    private javax.swing.JButton jb_crearU;
    private javax.swing.JButton jb_guardarU;
    private javax.swing.JDialog jd_crearU;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JSpinner sp_ki;
    private javax.swing.JTextField tf_planet;
    private javax.swing.JTextField tf_raza;
    // End of variables declaration//GEN-END:variables
    Universo enCreacion;
    ArrayList<Universo> universos;
}
